#!/bin/sh

# adding Onion feeds
echo "src/gz omega2_core http://repo.onioniot.com/omega2/packages/core
src/gz omega2_base http://repo.onioniot.com/omega2/packages/base
src/gz omega2_packages http://repo.onioniot.com/omega2/packages/packages
src/gz omega2_routing http://repo.onioniot.com/omega2/packages/routing
src/gz omega2_onion http://repo.onioniot.com/omega2/packages/onion" \
>> /etc/opkg/distfeeds.conf

# remove incompatible feeds
sed -i /openwrt_[obc]/d /etc/opkg/distfeeds.conf

exit 0
